# Deploy with `{golem}` {#deploy-golem}


It is essential to visualize its application very regularly during the development phase, and if possible under the same conditions as the production phase.


## Local deployment

A shiny application built from golem is _by definition_ encapsulated as an R package. To install your application on a computer with R, you "just" need to install the package you built.
From Rstudio in the project corresponding to the golem you built, the instruction `remotes::install_local()` will install your package on your computer. This corresponds to clicking on Build > Install Restart in the IDE.
To install your package on another computer, in a more conventional way, you will need to create a bundled version of you package. To do this `devtools:build()` will generate a .tar.gz file like `mygolem_0.0.1.tar.gz` you can share with others.

## Deploying Apps with `{golem}`

The `dev/03_deploy.R` file contains function for deploying on various plateforms. 


they are two main way to deploy a shiny app:
+ the Rstudio's solutions
+ the docker based solutions


## RStudio Environments

Rstudio propose 3 ways to deploy your shiny application, you can use  : 
+ shinyapps.io, this website will host your application
+ Shiny server is a software you have to install on your own server
+ Rstudio connect is a convenient way to deploy your application simply by clickin on the "blue button" from your Rstudio IDE. Rstudio connect is a software you have to install on your own server 


This 3 functions are respectivly dedicated to deploy on each solution

golem::add_rstudioconnect_file()
golem::add_shinyappsio_file()
golem::add_shinyserver_file()


This function create an `app.R` file you can use to deploy your app.

## Docker 

Docker is an open source and mainly free software that allows you to easily launch applications in software containers. Docker has become an essential solution in the devops world and a lots of solution are based on it.

To enjoy Docker, you can use the golem::add_dockerfile() function this will create a file called `Dockerfile` this is the recepie of a docker image that contains every instruction needed to run your application. It's mimic your developpement context ( R version, R package version...), and this allow you to create docker containers with your application.

One one the famous way to deploy shiny app using docker is to use ShinProxy, ShinyProxy is an open source solution wich will launch a new container for eahc new shiny user.

to have a shinyproxy-ready docker image, use the golem:add_dockerfile_shinyproxy().
Heroku is another platform to deploy your application, if you use this you can use golem::add_dockerfile_heroku()

this 3 functions contains somes parameters to tweak the Dockerfile you create. by default it use the sysreqs api (on sysreqs.r-hub.io) to detect the system dependencies needed to install R packag



Ressources : 


+ https://docs.docker.com/get-started/
+ https://www.shinyproxy.io/
+ https://www.heroku.com/

