--- 
title: "Building Big Shiny Apps - A Workflow"
author: "Colin Fay, Vincent Guyader, Cervan Girard, Sébastien Rochette"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
biblio-style: apalike
link-citations: yes
description: "Building Robust Shiny Application - A Workflow"
favicon: img/favicon.ico
---

# Introduction {-}

This book is still at a Work in Progress stage.

## Motivation {-}

This book will not __get you started with Shiny__, nor __talk about how to deploy into production and scale your app__. 
What we'll see is __the process of building the app__. 
Why? Lots of blog posts and books talk about starting to use shiny or putting apps in production. 
Very few (if any) talk about this grey area between getting started and pushing into production. 

So this is what this book is going to talk about: building Shiny application. 
We'll focus on the process, the workflow, and the tools we use at ThinkR when building big Shiny Apps.

Hence, if you're starting to read this book, we assume you have a working knowledge of how to build a small application, and want to know how to go one step further. 

## Book structure {-}

+ Part 1 (Building big Shiny Apps) gives a general context about what is a successful Shiny Apps and what challenges arise when you're dealing with a large scale application. 
It also introduces the `{golem}` package and more general concept about organising your workflow. 
This first part will be light on code: you'll read more about conceptual ideas and organisation strategy. 

+ Part 2 to 6 describes a series of steps you can take when you want to build a Shiny App, and the tooling associated with each step.

+ Part 7 (Optimizing) tackles the question of optimization, first by presenting some common caveats of Shiny Apps, and then showing how to optimize R code, and use JavaScript to lighten R work.

## About the authors {-}

// TODO 

## Want to help? {-}

Any feedbacks on the book is very welcome. 
Feel free to [open an issue](https://github.com/ThinkR-open/building-shiny-apps-workflow/issues), or to make a PR if you spot a typo (I'm not a native english speaker, so there might be some waiting to be found ;) ).

## Other resources {-}

### Getting started with Shiny  {-}

+ [Learn Shiny with RStudio](https://shiny.rstudio.com/tutorial/)
+ [Getting Started with Shiny](https://ourcodingclub.github.io/2017/03/07/shiny.html)
+ [(WIP) Mastering Shiny](https://github.com/jcheng5/shiny-book)
+ [A gRadual intRoduction to Shiny](https://laderast.github.io/gradual_shiny/)

### Shiny into production  {-}

+ [Shiny in production: Principles, practices, and tools](https://resources.rstudio.com/rstudio-conf-2019/shiny-in-production-principles-practices-and-tools-joe-cheng)
+ [Shiny in Production](https://kellobri.github.io/shiny-prod-book/)

[Suggest a Resource!](https://github.com/ThinkR-open/building-shiny-apps-workflow/issues)

## Acknowledgments {-}

// TODO : 

```{r echo = FALSE}
# Some internal funs
right_link <- function(text, link){
  htmltools::tagList(
    htmltools::singleton(
      htmltools::tags$style(
        ".right{ text-align: right;}"
      )
    ), 
    htmltools::tags$div(
      class = "right",
      htmltools::tags$a(
        href = link, 
        text
      )
    )
  )
}

with_tooltip <- function(text, tooltip){
  htmltools::tags$span(
    class = "tooltip", 
    text, 
    htmltools::tags$span(
      class="tooltiptext", 
      tooltip
    )
  )
}
```