# Don't rush into coding {#step-design}

## Designing before coding

> You have to believe that software design is a craft worth all the intelligence, creativity, and passion you can muster. Otherwise you won't look past the easy, stereotyped ways of approaching design and implementation; __you'll rush into coding when you should be thinking__. You'll carelessly complicate when you should be relentlessly simplifying — and then you'll wonder why your code bloats and debugging is so hard.

`r right_link("The Art of Unix Programming - Attitude Matters Too", "http://www.catb.org/~esr/writings/taoup/html/ch01s09.html")`

### The Urge to Code 

At the moment you receive the specifications for your app, it's tempting to rush into coding.
And that's perfectly normal: we're Shiny developer because we love building softwares, so as soon as a problem emerges, our brain starts thinking about technical implementation, packages, pieces of code, and all these things that we love to do when we're building an app.

Rushing into coding from the very beginning is not the safest way to go. 
Focusing on technical details from the very beginning can make you miss the big picture, be it for the whole app if you're in charge of the project, or for the piece of the whole app you've been assigned to. 
Have you ever faced a situation in a coding project where you tell yourself "Oh, I wish I had realised this sooner, because now I need to refactor a lot of my code for this specific thing"? 
Yes, we all have been in this situation: realising too late that the thing we've implemented doesn't work with another feature we discover along the road. 
And what about "Oh I wish I had realised sooner that this package existed before trying to implement my own fonctions to do that!.
Yes, same thing: we're jumping straight into solving programming problem when someone else has open-sourced a solution to this very same problem. 
Of course, implementing your own solution might be a good thing in specific cases: avoiding heavy dependencies, incompatible licensing, the joy of intellectual challenge... 
But when building production softwares, it's safer to go for an existing solution if it exists and fits in the project: existing packages / software benefit from wider testing, wider documentation, and a larger audience if you need to ask questions.

So, before rushing into coding, take some time to conceptualise your application / module on a piece of paper. 
That will help you get the big picture for the piece of code you'll be writing: what are the inputs, what are the outputs, what packages / services you can use inside your application, how it will fit in the rest of the project.

### About Concept Map

// TODO

## Ask questions

Before starting to code, the safe call will be to ask your team/client (depending on the project) a series of question just to get a good grasp of the whole project. 
Here is a (non-exhaustive) list of information you might need along the way. 

Side note: of course, these questions do not cover the core functionning of the application: I'm pretty sure you've thought about covering this already. 
These are more contextual questions which are not directly linked to the application itself  

### About the end users 

Who are the end users of your app? 
Are they tech-literate?
In which context will they be using your app? 
On what machines, and in what context?
Will they be using the app in their office, on their phone while driving a tractor, in a plant while wearing lab coats? 

That might seems like weird questions if you're just focusing on the very technical side of the app implementation, but think about where the app will be used: the application used while driving agricultural machineries might need less interactive things, bigger fonts, simpler interface, less details and more direct information. 
If you're building a Shiny app for a team of sellers who are always on the road, chances are they'll need an app that they can browse from their mobile. 
And developing for mobiles requires a different kind of mindeset^[
For developing an app that is mobile first, you can have a look at the great [`{shinyMobile}`](https://rinterface.github.io/shinyMobile/) package, made by the amazing Rinterface team.
].

Another good reason why talking to the users is an important step is that most of the time, people writing specifications are not the end users and will ask either for too much features or not enough. 
Do the users really need that much interactive plots? 
Do they actually need that much granularity in the information? 
Will they really read a `datatable` of 15k lines?
Do they really care about being able to zoom in the `dygraph` so that they can see the point at a minute scale?
To what extent does the app has to be fast?
Asking these questions is important, because building interactive wigets makes the app a little bit slower, and shoving a series of unnecessary widgets will make the user experience worse. 
The speed of execution of your app is also an important parameter for your application: getting a sense about the need for speed in your application will allow you to judge wether or not you'll have to focus on optimizing code execution.

On top of that, remember all these things we've seen in the last chapter about accessibility: some of your end users might have specific accessibility requirements.

### Pre-existing code-base

From time to time, you're building a Shiny app on top of an existing code-base: either scripts with business logic, a package if you're lucky, or a POC for a Shiny app.



### Deployment 

There are so many considerations about deployment that it will be very hard to list them all here, but keep in mind that if you don't ask questions about where to deploy your app from the start, you might have bad surprises when you'll send your app to production. 
Of course, it's more or less solved if you're deploying with Docker: if it works in a container on your machine, it should work in production. 

But that's just the tip of the iceberg. 
One time, we built an app that had to do some API requests.  
So far so good, nothing too complicated... until we discovered that the server where the app will be deployed doesn't have access to the internet, making it impossible to issue API requests from the server.
Here, the containers worked on our machine, as they had access to the internet. 
Once deployed, the app stopped working, and we lose a couple of days of exchanges with the client, trying to debug our API calls, until we realised that the issue wasn't with our app, but with the server itself. 

It's even more important to thing about the IT side of your application, as the people writing specs and interacting with you might come from the Data Science team, and they might or might not have discussed with the IT team about deploying the app, so there's a chance that they don't have in mind all what is needed to deploy a Shiny App on their company server. 
For example, maybe your application has a database backend.
For that, you'll need to have access to this database, the correct port should be set, and the permission given to the process that executes the Shiny app to read, and maybe write, to the database.
But, __and for good reason__, database managers don't issue read and write permissions to a DB without having examined what the app wants to read, and how and where it will write. 
So, if you don't want to have weeks of delay for your app deployment, start the discussion from the very beginning of the project. 
That way, even if the process of getting permission to write on the company database takes time, you might have it by the end of the coding marathon. 
