# (PART) Step 1: Designing {-}

# UX Matters {#uxmatters}

<!-- TO READ : -->

<!-- https://en.wikipedia.org/wiki/Principle_of_least_astonishment#cite_note-Raymond2004-1 -->
<!-- https://www.ibm.com/developerworks/web/library/us-cranky10/index.html -->
<!-- https://www.cs.tufts.edu/~nr/cs257/archive/mike-cowlishaw/rexx.pdf -->
<!-- https://books.google.fr/books?id=I-NOcVMGWSUC&pg=PA85&redir_esc=y#v=onepage&q&f=false -->
<!-- http://www.faqs.org/docs/artu/ch11s01.html -->
<!-- http://canonical.org/~kragen/tao-of-programming.html#book4 -->

We have a natural tendency, as R-coders, to be focused on the back-end, i.e the server part of the application
^[aka what happens in the server side of a Shiny App]. 
Which is perfectly normal—chances are you didn't come to R to code front-ends
^[Front-end are the visual parts of your application, the one with which your user interacts, as opposed to the back-end, which is what is installed on the server. 
In shiny, front-end is what correspond to the UI, back-end to the server.]. 
But let's state the truth: no matter how complex and innovative your backend is, your application is bad if your User Experience (UX) is bad. 
That's the hard truth. 
If people can't understand how to use your application, your application isn't successful, no matter how incredible the backend is. 
This natural taste for back-end / server logic can deserve you on the long run: by neglecting the UI, you'll make your application less likely to be adopted among your users. 
Which is a good way to fail your application project.

## _The Unbearable Lightness of Being_

// TODO

> "Simplify, then add lightness"

> __Colin Chapman CBE, Founder of Lotus Cars__

There are mainly two contexts where you'll be building a web app with R: one for professional use (i.e people will rely on this app to do their job), or for fun (i.e people will just use the app as a distraction). 
But in both cases, people will want the app to be useable, and __easily__ usable. 

If people will use your app in a professional context, they don't want to fight with your interface, read complexe manuals, or lose time understanding what is supposed to do what in your application. 
Think about all the professional applications and softwares that you've been ranting about during your professional life. 
You don't want your app to be one of that. On the other end, if users open your app for fun, they are not going to fight your app into submission: they are just going to give up using your app if it's too complex to be used. 

### Make a self-explanatory app

> All kinds of things on a Web page can make us stop and think unnecessarily. Take names, for example. Typical culprits are cute or clever names, marketing-induced names, company-specific names, and unfamiliar technical names.

`r right_link("'Don't make me think', Steve Krug", "http://www.sensible.com/dmmt.html")`

-> If things are clickable, it has to look clickable

> "As a user, I should never have to devote a millisecond of thought to whether
things are clickable—or not" 

`r right_link("'Don't make me think', Steve Krug", "http://www.sensible.com/dmmt.html")`

-> If there is a progression in your app, you should have a clear pattern of moving forward

-> If you need inputs, this should be made clear

-> Have some "reading logic": from left to right or right to left, there should be a progression in the way visual elements are organised.


### "Rule of Least Surprise"

"Rule of Least Surprise" or "Principle of Least Astonishment."

> Rule of Least Surprise: In interface design, always do the least surprising thing.

`r right_link("'Basic of the Unix Philosophy', Eric Steven Raymond", "http://www.catb.org/~esr/writings/taoup/html/ch01s06.html#id2878339")`

Try to find a simple, and efficient UI. 
One that people can understand and use in a matter of seconds. 
Don't implement features or visual elements that are not actually needed, just "in case". 
And spend time working on that UI, really thinking about what visual elements you are implementing. 

## The danger of over-featuring

### Restrain reactivity 

// TODO

As a designer, you think: they'll select this, and when they release the slider, this will update automatically. 
In real life, people make mistakes using the app, so if everything reacts to their every moves, the experience using the app can be bad.

### Too much interactivity 

// TODO

Don't make things interactive if there is no value in adding interactivity. 
Adding interactivity widgets (in most cases) means adding visual elements to your original content: in other words, you're adding visual components that might distract the user from focusing on the content of the information.

Good rule: don't add feature for the sake of adding a feature. 
Less is more.

Example: using `DT::data.table()` or `plotly` or `dygraph` when it's not needed. 

Maybe a parallel with 90/00 website design with a lot of visual noise vs minimalist modern design?


## About Accessibility 

// TODO

A user interface needs to be "ready to be consumed" by the broader audience possible. 
That means people with visual, mobility, or cognitive disabilities. 

Web Accessibility is pretty standard concept in the web development world, and you can learn about this straight from the first chapter of [learn.freecodecamp.org](https://learn.freecodecamp.org/). 
-> Screen to speech technology : html semantic tags
-> Mobility impairment, people w/ parkinson for example. Exemple of the text input & ENTER button. Making things keyboard friendly. 
-> ColorBlind, viridis

## Further reading 

// TODO

+ [_'Don't Make Me Think'_, Steve Krug](http://www.sensible.com/dmmt.html)

